# Generated by Django 3.0.5 on 2020-06-07 16:46

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Adı')),
                ('last_name', models.CharField(max_length=50, verbose_name='Soyadı')),
                ('birthday', models.DateTimeField(auto_now_add=True, verbose_name='Doğum Tarihi')),
            ],
        ),
        migrations.CreateModel(
            name='BaseBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50, verbose_name='Başlık')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Adı')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('basebook_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='book.BaseBook')),
                ('content', ckeditor.fields.RichTextField(verbose_name='İçerik')),
                ('book_image', models.FileField(blank=True, null=True, upload_to='', verbose_name='Kitaba Fotoğraf Ekleyebilirsiniz.')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Author', verbose_name='Yazar')),
                ('publisher', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='book.Publisher')),
            ],
            bases=('book.basebook',),
        ),
        migrations.CreateModel(
            name='WishAuthor',
            fields=[
                ('author_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='book.Author')),
            ],
            bases=('book.author',),
        ),
        migrations.CreateModel(
            name='WishPublisher',
            fields=[
                ('publisher_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='book.Publisher')),
            ],
            bases=('book.publisher',),
        ),
        migrations.CreateModel(
            name='WishBook',
            fields=[
                ('basebook_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='book.BaseBook')),
                ('author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='book.WishAuthor', verbose_name='Yazar')),
                ('publisher', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='book.WishPublisher')),
            ],
            bases=('book.basebook',),
        ),
        migrations.CreateModel(
            name='FavouriteBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='book.Book', verbose_name='Kitap')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_author', models.CharField(max_length=50, verbose_name='İsim')),
                ('comment_content', models.CharField(max_length=200, verbose_name='Yorum')),
                ('comment_date', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='book.Book', verbose_name='Kitap')),
            ],
            options={
                'ordering': ['-comment_date'],
            },
        ),
    ]
