# Generated by Django 3.0.5 on 2020-06-22 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basebook',
            name='title',
            field=models.CharField(default='', max_length=50, verbose_name='Kitap Adı'),
        ),
    ]
