# Generated by Django 3.0.5 on 2020-05-19 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20200513_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_image',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Kitaba Fotoğraf Ekleyebilirsiniz.'),
        ),
    ]
